gallery:
  spookyfoxinc/IMG_2298.jpg:
    id: ref
    artist: spookyfoxinc
    grid:
      w: 3
      h: 2
    meta:
      en:
        title: Avoonix Reference
        description:
          The dots above the eyes are eyebrows, not a fur pattern. The colors
          below are slightly different than the image - feel free to use either.
      de:
        title: Avoonix Referenz
        description: ""
    color: "#f3849c"
  spookyfoxinc/IMG_2338.png:
    id: jaq
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Hug
        description: ""
      de:
        title: Umarmung
        description: ""
    color: "#e864ca"
  spookyfoxinc/IMG_2723.png:
    id: qkf
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Please
        description: ""
      de:
        title: Bitte
        description: ""
    color: "#f6d2eb"
  spookyfoxinc/IMG_2724.png:
    id: uoT
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Heart
        description: ""
      de:
        title: Herz
        description: ""
    color: "#e95dc2"
  spookyfoxinc/IMG_2337.png:
    id: ceS
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Walkies??
        description: ""
      de:
        title: Gassi??
        description: ""
    color: "#e968cb"
  avoonix/day.png:
    id: qf0
    artist: avoonix
    grid:
      w: 2
      h: 2
    meta:
      en:
        title: Day
        description: ""
      de:
        title: Tag
        description: ""
    color: "#e5b6e1"
  spookyfoxinc/IMG_2761.png:
    id: xd2
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: "*blep*"
        description: ""
      de:
        title: "*Blep*"
        description: ""
    color: "#e965d0"
  spookyfoxinc/IMG_2762.png:
    id: pOY
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Yes
        description: ""
      de:
        title: Ja
        description: ""
    color: "#e75fd0"
  spookyfoxinc/IMG_2812.png:
    id: 2g6
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: "*pat pat*"
        description: ""
      de:
        title: "*pat pat*"
        description: ""
    color: "#ebd3ea"
  sinister-jordex/1608588792.jpg:
    id: mXG
    artist: sinister-jordex
    grid:
      w: 2
      h: 3
    meta:
      en:
        title: Avoo and Lou kissing
        description: ""
      de:
        title: Avoo und Lou küssen sich
        description: ""
    color: "#ac7f83"
  spookyfoxinc/IMG_2813.png:
    id: M8f
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Schadenfreude
        description: ""
      de:
        title: Schadenfreude
        description: ""
    color: "#bac5e2"
  spookyfoxinc/IMG_2814.png:
    id: P7y
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Sleeping
        description: ""
      de:
        title: Schlafen
        description: ""
    color: "#ef5cc9"
  spookyfoxinc/IMG_2828.png:
    id: PH9
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Spooning
        description: ""
      de:
        title: Löffeln
        description: ""
    color: "#748af7"
  spookyfoxinc/IMG_2829.png:
    id: OF8
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Licc
        description: ""
      de:
        title: Lecken
        description: ""
    color: "#f9d4e3"
  spookyfoxinc/IMG_2937.png:
    id: zdn
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Spreadeagle
        description: ""
      de:
        title: Fixiert
        description: ""
    color: "#becafb"
  spookyfoxinc/IMG_3043.png:
    id: o0B
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Avoo kissing Lou
        description: ""
      de:
        title: Avoo küsst Lou
        description: ""
    color: "#e369b8"
  toxxy-the-trash/avoonix_fursona1.png:
    id: fTQ
    artist: toxxy-the-trash
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: "Headshot"
        description: ""
      de:
        title: "Headshot"
        description: ""
    color: "#dcd"
  toxxy-the-trash/queen_of_diapers_avoo1.png:
    id: 2cM
    artist: toxxy-the-trash
    grid:
      w: 2
      h: 2
    meta:
      en:
        title: "Queen of diapers"
        description: ""
      de:
        title: "Queen der Windeln"
        description: ""
    color: "#e484b4"
  toxxy-the-trash/disgusting_queen_of_diapers_avoo1.png:
    id: Ayx
    artist: toxxy-the-trash
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: "Disgusting queen of diapers"
        description: ""
      de:
        title: "Ekelige Queen der Windeln"
        description: ""
    color: "#e386b0"
  toxxy-the-trash/vore1.png:
    id: Ewt
    artist: toxxy-the-trash
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: "Icon"
        description: ""
      de:
        title: "Icon"
        description: ""
    color: "#e391d7"
  zombineko/1b.png:
    id: Y3t
    artist: zombineko
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Avoo in diaper
        description: ""
      de:
        title: Avoo in Windel
        description: ""
    color: "#c7b7be"
  zombineko/1a.png:
    id: QFD
    artist: zombineko
    grid:
      w: 3
      h: 4
    meta:
      en:
        title: Avoo in diaper
        description: ""
      de:
        title: Avoo in Windel
        description: ""
    color: "#c6b8c3"
  zombineko/1c.png:
    id: BWU
    artist: zombineko
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Avoo in diaper
        description: ""
      de:
        title: Avoo in Windel
        description: ""
    color: "#c9b9bd"
  zombineko/1d.png:
    id: KVt
    artist: zombineko
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Avoo in diaper
        description: ""
      de:
        title: Avoo in Windel
        description: ""
    color: "#c9b9bb"
  zombineko/1e.png:
    id: S60
    artist: zombineko
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Avoo in diaper
        description: ""
      de:
        title: Avoo in Windel
        description: ""
    color: "#c9b9bb"
  zombineko/1g.png:
    id: QO5
    artist: zombineko
    grid:
      w: 2
      h: 2
    meta:
      en:
        title: Avoo in diaper
        description: ""
      de:
        title: Avoo in Windel
        description: ""
    color: "#c7b7be"
  zombineko/1f.png:
    id: sxf
    artist: zombineko
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Avoo in diaper
        description: ""
      de:
        title: Avoo in Windel
        description: ""
    color: "#c6b8c3"
  zombineko/1h.png:
    id: 8jM
    artist: zombineko
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Avoo in diaper
        description: ""
      de:
        title: Avoo in Windel
        description: ""
    color: "#c9b9bb"
  blumen/1606077033.jpg:
    id: kUy
    artist: blumen
    grid:
      w: 2
      h: 2
    meta:
      en:
        title: Avoo and Lou kissing
        description: ""
      de:
        title: Avoo und Lou küssen sich
        description: ""
    color: "#846571"
  valdith-zam/1608587106.png:
    id: wtB
    artist: valdith-zam
    grid:
      w: 2
      h: 2
    meta:
      en:
        title: Avoo and Lou kissing
        description: ""
      de:
        title: Avoo und Lou küssen sich
        description: ""
    color: "#edacbc"
  spookyfoxinc/IMG_2938.png:
    id: 7Ev
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Ass
        description: ""
      de:
        title: Arsch
        description: ""
    color: "#d96fd5"
  spookyfoxinc/IMG_2939.png:
    id: V9n
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: I can't see!
        description: ""
      de:
        title: Ich kann nichts sehen!
        description: ""
    color: "#f164ca"
  spookyfoxinc/IMG_2999.png:
    id: xZs
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Horny jail
        description: ""
      de:
        title: Geiles Gefängnis
        description: ""
    color: "#e680c2"
  adopt-empire/1603980707.jpg:
    id: Ggo
    artist: adopt-empire
    grid:
      w: 2
      h: 3
    meta:
      en:
        title: Avoo and Lou hugging
        description: ""
      de:
        title: Avoo und Lou umarmen sich
        description: ""
    color: "#653640"
  spookyfoxinc/IMG_3001.png:
    id: jSj
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Milk
        description: ""
      de:
        title: Milch
        description: ""
    color: "#fad3d9"
  spookyfoxinc/IMG_3002.png:
    id: eVS
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Avoo presenting paws
        description: ""
      de:
        title: Avoo präsentiert seine Pfoten
        description: ""
    color: "#f7d3f2"
  spookyfoxinc/IMG_3075.png:
    id: V7O
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Lou going for walkies with Avoo
        description: ""
      de:
        title: Lou geht mit Avoo gassi
        description: ""
    color: "#4d274b"
  spookyfoxinc/IMG_3076.png:
    id: Fxg
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Lou pinning Avoo
        description: ""
      de:
        title: Avoo festgehalten von Lou
        description: ""
    color: "#9d6d7d"
  spookyfoxinc/IMG_3077.png:
    id: Y66
    artist: spookyfoxinc
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Lou on Avoo
        description: ""
      de:
        title: Lou auf Avoo
        description: ""
    color: "#d77db1"
  asgardianartist/avoonix.png:
    id: XAG
    artist: asgardianartist
    grid:
      w: 2
      h: 3
    meta:
      en:
        title: Fullbody
        description: ""
      de:
        title: Ganzkörper
        description: ""
    color: "#e763c0"
  heridag/20201006_181134.png:
    id: JK0
    artist: heridag
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Avoo is sus
        description: ""
      de:
        title: Avoo ist sus
        description: ""
    color: "#be4aa3"
  heridag/20201006_181450.png:
    id: MKd
    artist: heridag
    grid:
      w: 1
      h: 1
    meta:
      en:
        title: Avoo is sus
        description: ""
      de:
        title: Avoo ist sus
        description: ""
    color: "#be4aa3"
artists:
  spookyfoxinc:
    url: https://www.spookyfoxinc.com/
  avoonix:
    url: https://avoonix.com/
  asgardianartist:
    url: https://linktr.ee/asgardian.artist
  heridag:
    url: https://linktr.ee/Heridag
  sinister-jordex:
    url: https://www.furaffinity.net/user/sinister-jordex
  valdith-zam:
    url: https://www.furaffinity.net/user/valdith-zam
  blumen:
    url: https://www.furaffinity.net/user/blumen
  adopt-empire:
    url: https://www.furaffinity.net/user/adoptempire
  zombineko:
    url: https://www.furaffinity.net/user/zombineko
  toxxy-the-trash:
    url: "https://steamcommunity.com/id/toxxythetrash"
